// Customer related events
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';

// Restaurant related events
export const RESTAURANT_SIGNUP = 'RESTAURANT_SIGNUP';
export const RESTAURANT_LOGIN = 'RESTAURANT_LOGIN';
// Common events
export const LOGOUT = 'LOGOUT';

// =========================

export const CUSTOMER_PROFILE_GET_SUCCESS = 'CUSTOMER_PROFILE_GET_SUCCESS';
export const CUSTOMER_PROFILE_GET_FAILED = 'CUSTOMER_PROFILE_GET_FAILED';

export const CUSTOMER_PROFILE_UPDATE_SUCCESS = 'CUSTOMER_PROFILE_UPDATE_SUCCESS';
export const CUSTOMER_PROFILE_UPDATE_FAILED = 'CUSTOMER_PROFILE_UPDATE_FAILED';

// Restaurant related events

export const RESTAURANT_PROFILE_GET_SUCCESS = 'RESTAURANT_PROFILE_GET_SUCCESS';
export const RESTAURANT_PROFILE_GET_FAILED = 'RESTAURANT_PROFILE_GET_FAILED';

export const RESTAURANT_PROFILE_UPDATE_SUCCESS = 'RESTAURANT_PROFILE_UPDATE_SUCCESS';
export const RESTAURANT_PROFILE_UPDATE_FAILED = 'RESTAURANT_PROFILE_UPDATE_FAILED';



