// Customer related
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const CUSTOMER_LOGIN = 'CUSTOMER_LOGIN';
export const CUSTOMER_PROFILE_GET = 'CUSTOMER_PROFILE_GET';
export const CUSTOMER_PROFILE_UPDATE = 'CUSTOMER_PROFILE_UPDATE';
export const UPLOAD_CUST_IMAGE ='UPLOAD_CUST_IMAGE';

// Restaurant related
export const RESTAURANT_SIGNUP = 'RESTAURANT_SIGNUP';
export const RESTAURANT_LOGIN = 'RESTAURANT_LOGIN';
export const RESTAURANT_PROFILE_GET = 'RESTAURANT_PROFILE_GET';
export const RESTAURANT_PROFILE_UPDATE = 'RESTAURANT_PROFILE_UPDATE';
export const UPLOAD_REST_IMAGE = 'UPLOAD_REST_IMAGE';
export const UPLOAD_DISH_IMAGE = 'UPLOAD_DISH_IMAGE';

// Common
export const LOGOUT = 'LOGOUT';

// ========================

// Restaurant related events

export const RESTAURANT_PROFILE_GET_SUCCESS = 'RESTAURANT_PROFILE_GET_SUCCESS';
export const RESTAURANT_PROFILE_GET_FAILED = 'RESTAURANT_PROFILE_GET_FAILED';

export const RESTAURANT_PROFILE_UPDATE_SUCCESS = 'RESTAURANT_PROFILE_UPDATE_SUCCESS';
export const RESTAURANT_PROFILE_UPDATE_FAILED = 'RESTAURANT_PROFILE_UPDATE_FAILED';



